spring:
  profiles.active: prod
  sql.init.mode: always
  datasource:
#    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_ip}
    username: ${db_username}
    password: ${db_password}
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

---

spring.config.activate.on-profile: prod
security.jwt.token:
  secret-key: ${secret-key}
  expire-length: ${jwt-validity}
